ci: exit

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -126,7 +126,7 @@ jobs:
     steps:
     - name: Fail when Corresponding Build wouldn't succeeded
       if: ${{needs.build.result != 'success' }}
-      run: echo "BUILD FAILED" >&2; xit 1
+      run: echo "BUILD FAILED" >&2; exit 1
     - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       id: download
